### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by g3wanghc** [Developers-Foundation/developers-foundation.github.io#2]
The current [site](https://developers-foundation.github.io) is hosting the default [README.md](https://github.com/Developers-Foundation/developers-foundation.github.io/blob/master/README.md) from the repo.

![image](https://user-images.githubusercontent.com/7648872/27503103-45c0a6c0-582e-11e7-8ea7-049fb897361e.png)

The listed site(s) don't actually have a link and is very misleading.

What is the purpose of [tse.html](https://github.com/Developers-Foundation/developers-foundation.github.io/blob/master/tse.html)?

**Comment by fady-json** [comment]
wops forgot to revert it back (Y) - give me a min @g3wanghc

**Comment by fady-json** [comment]
done (Y) close?

**Comment by g3wanghc** [comment]
@Fadyazmy please refer to the code change, and what does tse.html do?

**Comment by g3wanghc** [comment]
oh nvm, are you just gonna dump the landing page of all future projects in the home/dir for the repo?

**Comment by fady-json** [comment]
Correct, any static html products will be part of this repo like with TSE. If a product needs some server side code, it'll be on Heroku but also listed in the README like with Dolly Children.

**Comment by g3wanghc** [comment]
Fixed incorrect repo structure b21eea6e7b40c2cd0af6ffa7d0fca521d70e4a89.
